jobs:

- job: 'Linux'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip setuptools poetry && poetry install
    displayName: 'Install dependencies'

  - script: |
      poetry run pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()